apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.awsAccessKeyId | b64enc | quote }}
  aws_secret_access_key: {{ .Values.awsSecretAccessKey | b64enc | quote }}
